version: '3'
services:
  db:
    image: postgres:9.6
    ports:
      - 5440:5432
    env_file:
      - .env
  redis:
    image: redis
    ports:
      - 6381:6379
  rails:
    build: .
    command: sh -c 'cd /app/dispatch && bundle install && rails s -b 0.0.0.0'
    stdin_open: true
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
    volumes:
      - .:/app/dispatch
      - dispatch-gems:/usr/local/bundle
    tty: true
    env_file:
      - .env
  sidekiq:
    build: .
    command: sh -c 'cd /app/dispatch && sidekiq'
    stdin_open: true
    depends_on:
      - redis
    volumes:
      - .:/app/dispatch
      - dispatch-gems:/usr/local/bundle
    tty: true
    env_file:
      - .env
volumes:
  dispatch-gems:
    driver: local
