default:      &default
  adapter:    postgresql
  encoding:   unicode
  pool:       5
  username:   den
  password:   '123456789'
  host:       localhost # Swap in production
  port:       5432

development:
  <<:         *default
  database:   dispatch

test:
  <<:         *default
  database:   db/test.postgresql

production:
  <<:         *default
  database:   dispatch
  database:   db/production.postgresql
