default:     &default
  adapter:   postgresql
  encoding:  unicode
  pool:      <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username:  den
  password:  '123456789'

development:
  <<:        *default
  database:  dispatch
  host:      localhost

test:
  <<:        *default
  database:  db/test.postgresql

production:
  <<:        *default
  database:  dispatch
  host:      https://dispatch-application.herokuapp.com/
  database:  db/production.postgresql
