# send_daily:
#   cron: "0 14 * * *"
#   class: "DailyNewsDeliverJob"
#   queue: default
#
# send_weekly:
#   cron: "0 14 * * sun"
#   class: "WeeklyNewsDeliverJob"
#   queue: default

send_daily:
  cron: "* * * * *"
  class: "DailyNewsDeliverJob"
  queue: default

send_weekly:
  cron: "* * * * *"
  class: "WeeklyNewsDeliverJob"
  queue: default
